### ISSUE TITLE
Big windows title bar - Feature Request for a compact version

### ISSUE THREAD

**Issue by ajay230ps** [lassekongo83/adw-gtk3#158]
### Describe the issue

The hight of  the windows title bar is big which is not an issue for full HD display. However on my laptop which 1366 x 768 (15.6 inch) looks big.

Hence requesting you for a compact version of adw-gtk theme and if possible support for libadwaita.

On the below Screenshot. My taskbar hight is 32 pix. But windows title bar is big when compared to the taskbar.

### Screenshot(s)

https://imgur.com/a/0jfCbMK

### Versions

- OS and version: [Fedora 36]
- GNOME Version: [42.3]

### Settings

- [ ] I installed the theme from the tar.xz file.
- [x] I installed the theme from git with ninja-build.
- [ ] I installed the theme from elsewhere. (Where?)
- [x] The theme is the latest available version/git commit.
- [ ] I've installed the light flatpak theme: `org.gtk.Gtk3theme.adw-gtk3`
- [ ] I've installed the dark flatpak theme: `org.gtk.Gtk3theme.adw-gtk3-dark`
- [x] The file `~/.config/gtk-3.0/gtk.css` does not exist or is empty.
- [ ] Dark theme only: I've changed the theme to adw-gtk3-dark in gnome-tweaks AND set the appearance to dark in gnome-control-center.
- [ ] Before opening this issue I logged out of GNOME and then logged back in again.

**Comment by lassekongo83** [comment]
Add to `~/.config/gtk-4.0/gtk.css`

```css
headerbar {
  min-height: 38px;
}

headerbar button {
  margin-top: 4px;
  margin-bottom: 4px;
}

headerbar button:not(.close):not(.maximize):not(.minimize) {
  padding: 2px 4px;
}

windowcontrols button {
  padding-top: 0;
  padding-bottom: 0;
}

headerbar button.image-button {
  min-width: 22px;
  padding-left: 2px;
  padding-right: 2px;
}

headerbar button.toggle {
  padding: 0;
}

headerbar entry {
  margin-top: 0px;
  margin-bottom: 0px;
}
```

Then create a symbolic link to the gtk-3.0 folder: `ln -s  ~/.config/gtk-4.0/gtk.css  ~/.config/gtk-3.0/gtk.css`

There is no official support for compact mode because of general wonkiness. Some bugs may appear in libadwaita apps that have a sidebar. Also nautilus pathbar looks ugly.
