### ISSUE TITLE
Make CSD and SSD titlebars the same height

### ISSUE THREAD

**Issue by zehkira** [lassekongo83/adw-gtk3#177]
SSD titlebars are shorter than CSD ones. This makes the theme look inconsistent. I think it would be good to make them the same height.

As a temporary workaround, I've added this to my `~/.config/gtk-3.0/gtk.css`:
```css
.ssd .titlebar {
	min-height: 46px;
}
```
