### ISSUE TITLE
Purism Chatty SMS send button

### ISSUE THREAD

**Issue by julianfairfax** [lassekongo83/adw-gtk3#223]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [ ] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

The send button in Purism Chatty (https://source.puri.sm/Librem5/chatty) is unthemed.

### OS and version [e.g Fedora 37]

Mobian latest

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.5, Debian repo (tar.xz)

### GNOME version

Phosh 0.24.0

### Application name and version (If the issue is with an app.)

Chatty 0.7.1

**Comment by lassekongo83** [comment]
I can't test this at the moment. But does adding:

```css
.button_send_green:not(:disabled) {
  background: #6cba3d;
  border-color: #6cba3d;
  color: white;
  outline-color: rgba(255, 255, 255, 0.3);
  -gtk-icon-shadow: 0 -1px rgba(0, 0, 0, 0.543529);
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.4);
}
```
to `~/.config/gtk-3.0/gtk.css` do anything to the button. (You'll probably need to relog after adding that.)

**Comment by lassekongo83** [comment]
A [gtk inspector](https://wiki.gnome.org/Projects/GTK/Inspector) screenshot of the tree and any css classes would be helpful.

**Comment by lassekongo83** [comment]
Hmm. The class is correct from my other gtk.css solution. But that didn't work. Try adding this to `~/.config/gtk-3.0/gtk.css`

```css
button.button_send_green {
  background-color: pink;
}
```

And then relog to make sure. Does that do anything to the button?
