### ISSUE TITLE
Shadows aren't click-through

### ISSUE THREAD

**Issue by notpeelz** [lassekongo83/adw-gtk3#228]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

[shadow-arent-clickthrough.webm](https://github.com/lassekongo83/adw-gtk3/assets/920910/8209037b-51f1-4d77-af66-91fce2639e1d)

### OS and version [e.g Fedora 37]

Arch

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

4.6.r1.c301933-1 (AUR: adw-gtk3-git)

### GNOME version

44.1 (Wayland)

### Application name and version (If the issue is with an app.)

Curiously, this only happens with X11 programs. Wayland programs work fine.

kitty 0.28.1-2 (forced X11): bugged
obs-studio 29.0.2-5 (forced X11): bugged
discord 0.0.27 (flatpak, X11): bugged
virt-manager 4.1.0-2 (wayland): OK
chromium 113.0.5672.92-1 (wayland): OK
file-roller 43.0-2 (wayland): OK

**Comment by lassekongo83** [comment]
I don't think this is an issue with the theme. Probably a wayland/xwayland bug.

**Comment by notpeelz** [comment]
You may be right. I don't remember running into this issue before upgrading to GNOME 44.1 (from 43.5)

**Comment by slanderous-mambo** [comment]
This affects adw-gtk3 more than regular GTK3 Adwaita, because the shadows here are wider (like they are in libadwaita). Using old Adwaita, the bug is barely noticable.
Since I find this pretty annoying but want to keep using adw-gtk3, I fumbled around with the shadows in libadwaita.css. If anyone else is interested, this is what I set as a workaround:

```css
window.csd { box-shadow: 0 1px 3px 3px transparent, 0 2px 8px 2px rgba(0, 0, 0, 0.26), 0 0 0 1px rgba(0, 0, 0, 0.05); margin: 0px; border-radius: 12px; outline: 1px solid rgba(255, 255, 255, 0.07); outline-offset: -1px; }
window.csd:backdrop { box-shadow: 0 1px 3px 3px rgba(0, 0, 0, 0.09), 0 2px 8px 2px rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.02); transition: box-shadow 200ms ease-out; }
window.csd.dialog.message { box-shadow: 0 2px 8px 2px rgba(0, 0, 0, 0.14), 0 0 0 1px rgba(0, 0, 0, 0.05); }
```
