### ISSUE TITLE
Icons in Budgie Panel are cutoff at sides

### ISSUE THREAD

**Issue by Xrey274** [lassekongo83/adw-gtk3#239]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [ ] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [ ] I have created a new user profile without any modifications except adw-gtk3.

### Description

The icons in the Budgie Panel, are cut off on the sides. This happens only with adw-gtk3-dark, and no other theme (as show in below screenshots). This has been a thing for a while with different budgie  and adw-gtk3 versions.

## Adw-gtk3-dark
![Snapshot_2023-08-29_14-19-07](https://github.com/lassekongo83/adw-gtk3/assets/30723811/b166a69b-4757-4058-8b86-5b8d342ce9d6)

## Flat-Plat-dark (for example, other themes behave the same)
![Snapshot_2023-08-29_14-18-42](https://github.com/lassekongo83/adw-gtk3/assets/30723811/59919e86-0a73-4b20-bd8c-a6da473bbce5)

### OS and version [e.g Fedora 37]

Solus 4.4 

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

No idea, git main branch some time ago.

### GNOME version

44?

**Comment by lassekongo83** [comment]
Can you add the following to `~/.config/gtk-3.0/gtk.css`

```css
.budgie-panel button {
  min-height: 16px;
  min-width: 16px;
  padding: 0;
  border-radius: 0;
}

.budgie-panel.horizontal button {
  padding: 0 4px;
}

.budgie-panel.vertical button {
  padding: 4px 0;
}

.budgie-panel #tasklist-button {
  padding: 0 4px;
}

.budgie-panel.vertical #tasklist-button {
  min-height: 32px;
}

.budgie-panel button.flat.launcher {
  padding: 0;
}
```

Then relog (or restart the panel) and see if it fixes the problem.
