### ISSUE TITLE
Squared-off corners in wifi menu.

### ISSUE THREAD

**Issue by DuttaAB-dev** [lassekongo83/adw-gtk3#36]
![image](https://user-images.githubusercontent.com/61903332/154739268-d4f04957-4545-48f6-9255-b732a6bbc95c.png)
The heading is self-descriptive and this here is an example.

Simply put, the wifi list is having sharp corners.

**Comment by lassekongo83** [comment]
I found that non `.content` lists are a bit trickier to style. I have a style that sort of works, but it may have some bugs that can't be fixed. (`:last-child` border roundness not working, shadow artifacts, and applications that may break if the style is used.)

Try adding this to your `~/.config/gtk-3.0/gtk.css` and see if you notice any breakage or bugs in any apps.

```css
list.view.frame { padding: 0; background-color: #ffffff; color: rgba(0, 0, 0, 0.8); border-radius: 12px; box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.03), 0 1px 3px 1px rgba(0, 0, 0, 0.07), 0 2px 6px 2px rgba(0, 0, 0, 0.03); }
list.view.frame:backdrop { background-color: #ffffff; }
list.view.frame separator { margin: 0; background-color: #e1e1e1; }
list.view.frame > row { margin: 0; padding: 2px; transition: 200ms cubic-bezier(0.25, 0.46, 0.45, 0.94); border-radius: 12px; }
list.view.frame > row:not(:last-child) { border-bottom-left-radius: 0; border-bottom-right-radius: 0; }
list.view.frame > row:not(:first-child):not(:last-child) { border-radius: 0; -gtk-outline-radius: 0; }
list.view.frame > row:first-child { border-top-left-radius: 12px; border-top-right-radius: 12px; -gtk-outline-radius: 12px 12px 0 0; }
list.view.frame > row:last-child { border-top-left-radius: 0; border-top-right-radius: 0; border-bottom-left-radius: 12px; border-bottom-right-radius: 12px; -gtk-outline-radius: 0 0 12px 12px; }
list.view.frame > row:only-child { border-bottom: none; border-radius: 12px; -gtk-outline-radius: 12px; }
list.view.frame > row:not(:selected):hover { background-color: #f9f9f9; border-radius: 12px; }
```
