### ISSUE TITLE
Update the tab style to match with the new AdwTabBar style

### ISSUE THREAD

**Issue by rashidi77** [lassekongo83/adw-gtk3#87]
According to Alexander Mikhaylenko's tweet, AdwTabBar style has got updated. Which tab is selected should be much more obvious now, especially in dark variant or with only 2 tabs open.
Here are the screenshots of the new style : 
![image](https://user-images.githubusercontent.com/93915281/162569446-b9604d0d-11aa-4e65-b503-1ae3bcdbe1fa.png)
![image](https://user-images.githubusercontent.com/93915281/162569454-3b3b86e5-2a72-4a06-bee3-5b208d4582fa.png)

I think adw-gtk3 theme should be updated as well to match with the new style.

**Comment by lassekongo83** [comment]
Is this coming for libadwaita in GNOME 42, or is it supposed to be released in a later version?

Just checked on gnome-console to see if the tabs could be mimicked. I got kind of close, except accurate separators seems to be impossible.

**Comment by rashidi77** [comment]
> Is this coming for libadwaita in GNOME 42

I think it's not related to Gnome version. It's an update for Libadwaita itself and there is a plan to backport it to the already existing Libadwaita version. I'm not a developer so don't know specific details, but I saw a merged MR in the Libadwaita gitlab repo : https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/513

**Comment by Radical4ever** [comment]
I saw its finally merged, and nautilus 43 alpha now has this style of tabs. Elementary os has this style with gtk3 on their terminal. So it will be awesome if this is part of the theme :3

**Comment by lassekongo83** [comment]
It would be interesting to see the css for the elementary terminal to see if/how they did separators, but I can't find any source files. :(

**Comment by Radical4ever** [comment]
> It would be interesting to see the css for the elementary terminal to see if/how they did separators, but I can't find any source files. :(

Maybe its part of the stylesheet theme, but i going to see if its there something 😃

**Comment by Radical4ever** [comment]
> It would be interesting to see the css for the elementary terminal to see if/how they did separators, but I can't find any source files. :(

Maybe its part of the elementary theme (the elememtary stylesheet)

**Comment by lassekongo83** [comment]
Can't find anything recent there: https://github.com/elementary/stylesheet/blob/master/src/gtk-3.0/widgets/_notebooks.scss

**Comment by Radical4ever** [comment]
Guess we'll have to wait until a way is possible to do it

**Comment by zoli111** [comment]
What do you think about this?
This code adds separators to the left side of tabs, except for the first tab, the checked and the hovered tab and the ones before them.

```css
tabs > tab {
	margin: 4px 0;
	box-shadow: -1 0 0 0 white;
	/*Eg. 4px less tall separators*/
	/*box-shadow: -5 0 0 -4 white;*/
	margin-left: 1px;
}

tabs > arrow:down + tab,
tabs > tab.first-child {
	box-shadow: none;
}

tabs > tab:checked + tab,
tabs > tab:checked,
tabs > tab:hover + tab,
tabs > tab:hover {
	box-shadow: none;
	border-radius: 8px;
}
```
![image of my nautilus instalnce](https://user-images.githubusercontent.com/57037245/182918952-02d5e7ba-aa29-4321-a946-8346be713d7e.png)

**Comment by lassekongo83** [comment]
Kind of, but it has to be only on the .reorderable-page and libhandy tabbar tabs. [I made a branch with some of these changes](https://github.com/lassekongo83/adw-gtk3/tree/tabs-rework). I use a background-image instead of box-shadow as it work better with border-radius.

**Comment by zoli111** [comment]
Sure, I just wanted to show you this somewhat hacky solution, because I did similar while working on my theme. I hope it could help a bit.

**Comment by zoli111** [comment]
I have tested the changes. It looks good except for the  `:backdrop` styling which looks like this.
![light](https://user-images.githubusercontent.com/57037245/183070769-20d67024-9b23-4240-8aff-2e34a2669a9f.png)
![dark](https://user-images.githubusercontent.com/57037245/183071050-17f05cbe-365c-4025-8e39-2c54d8609b41.png)

**Comment by Radical4ever** [comment]
> I have tested the changes. It looks good except for the `:backdrop` styling which looks like this. ![light](https://user-images.githubusercontent.com/57037245/183070769-20d67024-9b23-4240-8aff-2e34a2669a9f.png) ![dark](https://user-images.githubusercontent.com/57037245/183071050-17f05cbe-365c-4025-8e39-2c54d8609b41.png)

I love it!!

**Comment by zoli111** [comment]
> tabs > arrow:down + tab,

I made a mistake here: `arrow.down` should be used instead of `arrow:down`. This should fix the separator appearing before the first tab.

**Comment by lassekongo83** [comment]
These new styles should be working now. Maybe there are some bug here and there. If nothing comes up I'll add it to main branch if the new libadwaita changes makes it to stable.

**Comment by Radical4ever** [comment]
i tried the branch and, its pretty cool (nautilus almost looks like his gtk4 beta 😄) just the tabs looks a bit collapsed to each other, you find any solution to that?

**Comment by abuhuraira0099** [comment]
The new style works everywhere except in Epiphany 43 Nightly Flatpak. 
![Screenshot from 2022-08-16 10-14-18](https://user-images.githubusercontent.com/79898595/184796707-daa689c1-8d71-4139-910d-d7f1629a7820.png)

**Comment by zoli111** [comment]
I tested Libadwaita apps on the upcoming Fedora beta, and there are no separators next to tabs in `:hover` state like in my sample code I sent this thread. I also measured the spacing between (5px) and around tabs (also 5px).

So I made some changes in my code sample which should fully mimic the new Libadwaita tabs' appearance.

```css
tabs {
	/*complement spacing around all tabs to 5px*/
	padding: 5px 2px 5px 3px;	
}

/*No need to set border-radius here, because tabs have the same background color as their surroundings*/
tabs > tab {
	/*Make shadowbox 4px narrower, and offset it by -5px horizontally to make 1px wide line*/
	box-shadow: -5px 0 0 -4px gray;
	/*Border is used to put the line to the center of the space between tabs*/
	/*Padding cannot be used because already set*/
	border-left: 2px solid transparent;
	margin-right: 3px;
}

tabs > arrow.down + tab,
tabs > tab:first-child,
tabs > tab:checked + tab,
tabs > tab:hover + tab {
	box-shadow: none;
}

tabs > tab:checked,
tabs > tab:hover {
	box-shadow: none;
	border-radius: 8px;
	/*Use margin and reset border when tabs are focused/selected*/
	border-left: none;
	margin-left: 2px;
}
```
Image:
![tabs1](https://user-images.githubusercontent.com/57037245/186179970-118737d6-f754-49a9-9f9f-653f78b85934.png)
Tab backgrounds and borders visualized with colors:
![tabs2](https://user-images.githubusercontent.com/57037245/186184021-8a6ffcf5-3281-4397-bea4-db64233543e4.png)
